bf16: true
cutoff_len: 4096
dataset: my_custom_train
dataset_dir: data
ddp_timeout: 180000000
do_train: true
double_quantization: true
enable_thinking: true
eval_steps: 20
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 16
include_num_input_tokens_seen: true
learning_rate: 3.0e-05
logging_steps: 5
lora_alpha: 32
lora_dropout: 0.1
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: D:\wxk_program\models\Qwen2.5-7B-Instruct
num_train_epochs: 4.0
optim: adamw_torch
output_dir: saves\Qwen2.5-7B-Instruct\lora\train_2026-04-06-18-59-54
packing: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
quantization_bit: 4
quantization_method: bnb
report_to: tensorboard
save_steps: 20
stage: sft
template: qwen
trust_remote_code: true
val_size: 0.045
warmup_steps: 17
